[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 manage.py migrate --noinput && python3 -m gunicorn recovery_center.wsgi --log-file - --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
